name: NLP Text Classification MLOps CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  mlops-pipeline:
    runs-on: ubuntu-latest

    env:
      AML_SUBSCRIPTION_ID: ${{ secrets.AML_SUBSCRIPTION_ID }}
      AML_RESOURCE_GROUP: ${{ secrets.AML_RESOURCE_GROUP }}
      AML_WORKSPACE: ${{ secrets.AML_WORKSPACE }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install -r azureml-environment-setup/conda_dependencies.txt || true  # If you keep conda.yml there

      - name: Run data validation
        run: python src/data_validation.py

      - name: Preprocess data
        run: python src/preprocessing.py

      - name: Train model and log to MLflow
        run: python src/train.py

      - name: Evaluate model
        run: python src/evaluate.py

      - name: Register model to Azure ML
        run: python src/register_model.py
