name: NLP-Text-Classification-Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  build-train-eval-register:
    runs-on: ubuntu-latest

    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install azure-ai-ml mlflow joblib

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create necessary folders
      run: |
        mkdir -p data/raw
        mkdir -p data/processed
        cp data/nlp_text_classification_dataset_2000.csv data/raw/

    - name: Run data validation
      run: python src/data_validation.py

    - name: Run preprocessing
      run: python src/preprocessing.py

    - name: Train model (with Azure MLflow tracking)
      run: python src/train.py

    - name: Evaluate model
      run: python src/evaluate.py

    - name: Register model
      run: python src/register_model.py

    - name: Deploy model
      run: python src/deploy_model.py

    - name: Upload model artifacts
      uses: actions/upload-artifact@10f09e3e3774c802d2c767a5b3a366e2e2b624c2
      with:
        name: model-artifacts
        path: models/
    
