name: NLP Text Classification CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  actions: read

jobs:
  train-and-deploy:
    runs-on: ubuntu-latest

    env:
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
      AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements.txt
        pip install azure-ai-ml mlflow joblib scikit-learn pandas

    - name: Azure Login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Create required folders
      run: |
        mkdir -p data/raw
        mkdir -p data/processed
        mkdir -p models
        cp data/nlp_text_classification_dataset_2000.csv data/raw/ || true

    - name: Run Data Validation
      run: python src/data_validation.py

    - name: Run Preprocessing
      run: python src/preprocessing.py

    - name: Train Model and Log to Azure MLflow
      run: python src/train.py

    - name: Evaluate Model and Log Metrics to Azure MLflow
      run: python src/evaluate.py

    - name: Upload Model Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: model-artifacts
        path: models/
