name: NLP Text Classification MLOps CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
  AZURE_RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
  AZURE_WORKSPACE_NAME: ${{ secrets.AZURE_WORKSPACE_NAME }}

jobs:
  mlops_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Create necessary folders
      run: |
        mkdir -p data/raw
        mkdir -p data/processed

    - name: Copy dataset (only if stored in repo)
      run: cp data/nlp_text_classification_dataset_2000.csv data/raw/

    - name: Run data validation
      run: python src/data_validation.py

    - name: Run preprocessing
      run: python src/preprocessing.py

    - name: Train model
      run: python src/train.py

    - name: Evaluate model
      run: python src/evaluate.py

    - name: Register model
      run: python src/register_model.py

    - name: Deploy model
      run: python src/deploy_model.py
